### ISSUE TITLE
Use indexpath="" on GRIB files

### ISSUE THREAD

**Issue by pmav99** [pmav99/inspectds#3]
```
Can't create file 'GRIB/ssrd/ssrd_CDS_era5_2018.grib.923a8.idx'
Traceback (most recent call last):
  File "/home/mavropa/.local/pipx/venvs/inspectds/lib/python3.8/site-packages/cfgrib/messages.py", line 343, in from_indexpath_or_filestream
    with compat_create_exclusive(indexpath) as new_index_file:
  File "/scratch/mavropa/conda/jeodpp/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/mavropa/.local/pipx/venvs/inspectds/lib/python3.8/site-packages/cfgrib/messages.py", line 264, in compat_create_exclusive
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL)
OSError: [Errno 30] Read-only file system: 'GRIB/ssrd/ssrd_CDS_era5_2018.grib.923a8.idx'
Can't read index file 'GRIB/ssrd/ssrd_CDS_era5_2018.grib.923a8.idx'
Traceback (most recent call last):
  File "/home/mavropa/.local/pipx/venvs/inspectds/lib/python3.8/site-packages/cfgrib/messages.py", line 353, in from_indexpath_or_filestream
    index_mtime = os.path.getmtime(indexpath)
  File "/scratch/mavropa/conda/jeodpp/lib/python3.8/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: 'GRIB/ssrd/ssrd_CDS_era5_2018.grib.923a8.idx'
```

**Comment by MiaSongIC** [comment]
Have you solved this problem? I have the same error as you. But I have no idea about it.

**Comment by pmav99** [comment]
This is not a fatal error. Grib files try to create this `idx` file. If they fail to create it, e.g. due to permission errors, then this traceback get's thrown. The workaround is simple enough:

```
ds = xr.open_dataset("'/path/to/filename.grib", engine="cfgrib", backend_kwargs={'indexpath': ''})
```
This way the index file does not get created so there is no warning. 

Care to do a Pull Request?
