### ISSUE TITLE
[pipx] Cannot determine package name from spec

### ISSUE THREAD

**Issue by NikosAlexandris** [pmav99/inspectds#7]
I am trying to
```
pipx install 'git+https://github.com/pmav99/inspectds.git'
```
but I get
```bash
  ERROR: Command errored out with exit status 1:
   command: /tmp/tmp_rg9cnoj/bin/python /home/nik/.local/pipx/shared/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp0b5qvxbs
       cwd: /tmp/pip-req-build-_o9kujoi
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/home/nik/.local/pipx/shared/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/nik/.local/pipx/shared/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/nik/.local/pipx/shared/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/tmp/pip-build-env-dh_nw11_/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
      poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
    File "/tmp/pip-build-env-dh_nw11_/overlay/lib/python3.8/site-packages/poetry/core/factory.py", line 43, in create_poetry
      raise RuntimeError("The Poetry configuration is invalid:\n" + message)
  RuntimeError: The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)

  ----------------------------------------
WARNING: Discarding git+https://github.com/pmav99/inspectds. Command errored out with exit status 1: /tmp/tmp_rg9cnoj/bin/python /home/nik/.local/pipx/shared/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp0b5qvxbs Check the logs for full command output.
ERROR: Command errored out with exit status 1: /tmp/tmp_rg9cnoj/bin/python /home/nik/.local/pipx/shared/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp0b5qvxbs Check the logs for full command output.
Cannot determine package name from spec 'git+https://github.com/pmav99/inspectds'. Check package spec for errors.
```

Trying to understand if the error is caused by some local misconfiguration or if something needs to be updated in the repository.

**Comment by pmav99** [comment]
No, that's my bad. I will push a fix.
